FROM php:8.2-apache

# تفعيل الإضافات المطلوبة
RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    pkg-config \
    libssl-dev \
    && docker-php-ext-install curl

# نسخ ملفات البوت
COPY . /var/www/html/

# تعديل صلاحيات المجلد
RUN chmod -R 755 /var/www/html/
RUN chown -R www-data:www-data /var/www/html/

# فتح المنفذ
EXPOSE 80

CMD ["apache2-foreground"]